"""create_tables

Revision ID: 51a00696d541
Revises: 
Create Date: 2026-09-06 15:32:47.474836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51a00696d541'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('standard_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('latest_version', sa.String(), nullable=True),
    sa.Column('mandatory_certification', sa.String(), nullable=True),
    sa.Column('download_link', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_id'), 'standards', ['id'], unique=False)
    op.create_index(op.f('ix_standards_standard_number'), 'standards', ['standard_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standards_standard_number'), table_name='standards')
    op.drop_index(op.f('ix_standards_id'), table_name='standards')
    op.drop_table('standards')
    # ### end Alembic commands ###
